### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by Nicoretti** [exasol/bucketfs-python#2]
## Summary
Make sure the documentation is easy to use (e.g. all parameters in the API documentation are shown properly).

Examples:
[Good](https://pyserial.readthedocs.io/en/latest/pyserial_api.html) vs [Bad](https://exasol.github.io/bucketfs-utils-python/main/api/exasol_bucketfs_utils_python.bucketfs_utils.html#module-exasol_bucketfs_utils_python.bucketfs_utils)

# Tasks
- [ ] Make sure everything is documented properly
- [ ] Add an examples section
- [ ] Make sure code snippets are run or taken as part unit tests
      (Doctests may be also an option, if they can be displayed easily within the docs using sphinx)
- [ ] Adjust old references from `bucketfs-util-python` to `bucketsfs-python`
- [ ] Add pypi based installation guide

# Resources
* https://www.sphinx-doc.org/en/master/usage/extensions/doctest.html
* https://www.sphinx-doc.org/en/master/usage/extensions/viewcode.html
* https://sphinx-tutorial.readthedocs.io/step-3/
* https://docs.python.org/3/library/doctest.html
* https://dannguyen.github.io/danssphinx-template/content/001-examples/500-partials.html
