### ISSUE TITLE
🔧 Cleanup and migrate integration tests and setup

### ISSUE THREAD

**Issue by Nicoretti** [exasol/bucketfs-python#41]
# Summary
All important integration tests for the old API should be migrated to the new API and made part of the integration tests suite of the new API. 

# Tasks
- [x] Use standard test directory layout
- [ ] Use Test markers
- [x] Use standard test ci workflows
- [x] Migrate and integrate UDF integration tests
- [x] Add pytest based Integration test settings/configuration
    - Buckets and DB settings used for integration tests
- [x] Add support for a pytest based setup of the integration tests (start db etc.)

**Comment by tkilias** [comment]
The package exasol_bucketfs_utils_python is not used anymore by any active public exasol repo, so we can remove it. With this we should also increase the major version.

**Comment by ckunki** [comment]
See also #43

**Comment by tkilias** [comment]
Use Test markers is not so important

**Comment by tkilias** [comment]
Everything was or will be more or less done in other tickets. For this reason, this ticket is obsolete.
