### ISSUE TITLE
🔧 Remove old BucketFs API and Package

### ISSUE THREAD

**Issue by Nicoretti** [exasol/bucketfs-python#43]
# Summary
Currently the `exasol-bucketfs` package contains two packages (`exasol.bucketfs`, `exasol_bucketfs_utils_python`) containing the new and the old API receptively. Once all dependencies to the old API are cut the `exasol_bucketfs_utils_python` package and their receptive tests should be removed.

## References
Requires this issues to be solved first:
* https://github.com/exasol/bucketfs-python/issues/41
* https://github.com/exasol/bucketfs-python/issues/42
* https://github.com/exasol/bucketfs-python/issues/153
* https://github.com/exasol/advanced-analytics-framework/issues/245

See also
* https://github.com/exasol/bucketfs-python/issues/186

# Task(s)
- [x] Remove old API package `exasol_bucketfs_utils_python`
- [x] Remove tests for `test_legacy` package
- [ ] Remove deprecated dependency
  - [ ] Joblib
  - [ ] Typeguard?

**Comment by tkilias** [comment]
The package exasol_bucketfs_utils_python is not used anymore by any active public exasol repo, so we can remove it. With this we should also increase the major version.
